---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fake-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fake-editor
  namespace: default
subjects:
- kind: ServiceAccount
  name: fake-user
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:unprivileged
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fake-user:psp:unprivileged
roleRef:
  kind: ClusterRole
  name: psp:unprivileged
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize specific service accounts (not recommended):
- kind: ServiceAccount
  name: fake-user
  namespace: default
